version: '1'
services:
  db:
    image: db-image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auras
      POSTGRES_DATABASE: pancreatic_cancer
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: app-image
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      #DATABASE_URL: 'postgres://postgres@db:5432/pancreatic_cancer'
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pancreatic_cancer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: auras
      restart: always
